name: HOC CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
    build:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
      
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Build
              run: |
                npm i --include=dev
                npm run lint
                npm run build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                path: 'dist'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
                
